export const PRODUCTREQ = "PRODUCTREQ"
export const PRODUCTSUC = "PRODUCTSUC"
export const PRODUCTREJ = "PRODUCTREJ"

export const SINGLEDATAREQ = "SINGLEDATAREQ"
export const SINGLEDATARES = "SINGLEDATARES"
export const SINGLEDATAREJ = "SINGLEDATAREJ"

export const DATAEDITREQ = "DATAEDITREQ"
export const DATAEDITREJ = "DATAEDITREJ"

export const DATADELETEREQ = "DATADELETEREQ"
export const DATADELETEREJ = "DATADELETEREJ"

export const USERREQ = "USERREQ"
export const USERRES = "USERRES"
export const USERREJ = "USERREJ"

export const USERLOGINREQ = "USERLOGINREQ";
export const USERLOGINRES = "USERLOGINRES";
export const USERLOGINREJ = "USERLOGINREJ";

export const USERSIGNOUTREQ = "USERSIGNOUTREQ";
export const USERSIGNOUTRES = "USERSIGNOUTRES";
export const USERSIGNOUTREJ = "USERSIGNOUTREJ";


export const POPUPSIGNINREQ = "POPUPSIGNINREQ";
export const POPUPSIGNINRES = "POPUPSIGNINRES";
export const POPUPSIGNINREJ = "POPUPSIGNINREJ";








 






